# docker compose 一般应用在单体单机应用中
version: "3.8"
# services ：我的这个docker compose由几个服务组成
services:
  mysql8:
    # 指定镜像版本
    image: mysql:8.0
    # 启动命令
    command: --default-authentication-plugin=mysql_native_password
    # 重启策略
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    # volumes 挂载文件 用来初始化数据库
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    # 指定端口映射关系
    ports:
      # -外部访问用13316端口
      - "13316:3306"
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
