apiVersion: v1
kind: Service
metadata:
  name: webook-record-redis
spec:
  selector:
    app: webook-record-redis
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3306
  type: LoadBalancer

