---
--- Generated by Luanalysis
--- Created by yangyiliy.
--- DateTime: 2023/11/11 13:00
---
local key = KEYS[1]
local cntKey = key..":cnt"
-- 用户输入的验证码
local expectedCode = AVGE[1]
local cnt = tonumber(redis.call("get",cntKey))
local code = redis.call("get",key)
if cnt == nil or cnt <= 0 then
    -- 验证次数耗尽
    return -1
end
if code == expectedCode then
    redis.call("set",cntKey,0)
    return 0
else
    redis.call("decr",cntKey)
    -- 用户输错了
    return -2
end
